# Credit to https://github.com/joeroe/risotto/blob/main/exampleSite/config.toml
baseURL = "https://salata.software"
theme = "risotto"
title = "Salata Software"
author = "John Salata"
copyright = "© [John Salata](https://github.com/jrsalata)<br>[View Source Code](https://github.com/jrsalata/jrsalata.github.io)"
pagination.pagerSize = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-horizon-dark"

# Sidebar: about/bio
[params.about]
title = "Salata Software"
description = "A personal blog exploring the challenges and adventures of a Computer Science student"


# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)

# Social Links
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jrsalata"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/john-salata"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:john@salata.software"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/Projects/"
weight = 10

[[menu.main]]
identifier = "honors"
name = "honors_e_portfolio"
url = "/honors/"
weight = 11

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 2
    ordered    = true
